<?php
namespace fileservice;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface GalleryServiceIf
{
    /**
     * @param \fileservice\Image[] $images
     * @return int
     * @throws \fileservice\FileError
     */
    public function saveFiles(array $images);
    /**
     * @param string[] $paths
     * @return string[]
     * @throws \fileservice\FileError
     */
    public function getFiles(array $paths);
    /**
     * @param string[] $paths
     * @return int
     * @throws \fileservice\FileError
     */
    public function deleteFiles(array $paths);
}
