<?php
namespace fileservice;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Image
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'file',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'path',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $file = null;
    /**
     * @var string
     */
    public $path = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['file'])) {
                $this->file = $vals['file'];
            }
            if (isset($vals['path'])) {
                $this->path = $vals['path'];
            }
        }
    }

    public function getName()
    {
        return 'Image';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->file);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->path);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Image');
        if ($this->file !== null) {
            $xfer += $output->writeFieldBegin('file', TType::STRING, 1);
            $xfer += $output->writeString($this->file);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->path !== null) {
            $xfer += $output->writeFieldBegin('path', TType::STRING, 2);
            $xfer += $output->writeString($this->path);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
